version: '3.4'

services:
  projeto-xp.api:
    image: ${DOCKER_REGISTRY-}projetoxpapi
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      DbServer: "mssql-db"
      DbPort: "1433"
      DbUser: "SA"
      Password: "${DB_PASSWD}"
      Database: "Users"
    ports:
      - "8880:80"
    volumes:
      - ./DockerLogs:/app/logs
    depends_on:
      - mssql-db
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: database
    user: root
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWD}"
      MSSQL_PID: Express
    ports:
      - "1450:1433"
    volumes:
    - ./DockerData:/var/opt/mssql/data
  php-website:
    container_name: website
    build:
      context: ../../projeto-xp.Website
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    volumes:
      - ../../projeto-xp.Website/website:/var/www/html
      - /var/www/html/vendor/